Sudoku.Web/Controllers/PuzzleController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Sudoku.Common;
using Sudoku.Core;
using Sudoku.Web.Models;

namespace Sudoku.Web.Controllers
{
    public class PuzzleController : Controller
    {
        // GET: Puzzle
        public ActionResult Index()
        {
            var model = new PuzzleViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult FileUpload(PuzzleViewModel model)
        {
            if (!ModelState.IsValid) return View("Index", model);

            var file = model.File;
            var fileText = string.Empty;
            if (file != null && file.ContentLength > 0)
            {
                using (var reader = new StreamReader(file.InputStream))
                {
                    fileText = reader.ReadToEnd();
                }
            }

            if (!string.IsNullOrEmpty(fileText))
            {
                var puzzleValues = FileReader.GetPuzzle(fileText);
                model.Puzzle = new Puzzle(model.PuzzleWidth, model.PuzzleHeight, 3, 3, new Alphabet { 1, 2, 3, 4, 5, 6, 7, 8, 9 });

                try
                {
                    model.Puzzle.LoadPuzzle(puzzleValues);
                    model.IsFileLoaded = true;
                }
                catch (InvalidPuzzleSizeException ex)
                {
                    ModelState.AddModelError("InvalidPuzzleSize", ex.ToString());
                }

                try
                {
                    model.Puzzle.Validate();          
                }
                catch (DuplicateValueException ex)
                {
                    model.IsFileLoaded = false;
                    ModelState.AddModelError("DuplicateValue", ex.ToString());
                }

                if (model.Puzzle.SolveCount == 0)
                {
                    model.IsFileLoaded = false;
                    ModelState.AddModelError("NoValues", "Your input file has no values");
                }
            }


            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Solve(PuzzleViewModel model, List<int> puzzleValues)
        {
            if (model != null && puzzleValues != null)
            {
                model.Alphabet = new Alphabet { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
                model.Puzzle = new Puzzle(model.PuzzleWidth, model.PuzzleHeight, 3, 3, model.Alphabet);

                try
                {
                    model.Puzzle.LoadPuzzle(puzzleValues);
                }
                catch (InvalidPuzzleSizeException ex)
                {
                    ModelState.AddModelError("InvalidPuzzleSize", ex.ToString());
                }

                var solver = new StrategySolver();
                solver.Strategies.Add(new BasicStrategy());

                solver.Solve(model.Puzzle);

                try
                {
                    model.Puzzle.Validate();
                }
                catch (DuplicateValueException ex)
                {
                    ModelState.AddModelError("DuplicateValue", ex.ToString());
                }

                if (!model.Puzzle.IsSolved)
                    ModelState.AddModelError("PuzzleNotSolved", "The puzzle was not solved");
            }

            return View("Index", model);
        }
    }
}

Sudoku.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Sudoku</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sudoku", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Puzzle Solver", "Index", "Puzzle")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>